monitor=DP-2,1920x1080@60,0x0,1
monitor=HDMI-A-1,1920x1080@144,1920x0,1
exec-once = swww img "/home/liox/Descargas/_.jpeg"
exec-once = hyprshade on mi_vibrance
env = QT_FFMPEG_DECODING_HW_DEVICE_TYPES,none
