# Monitor Configuration
# LG UltraGear (Main) - DP-2
monitor=DP-2, 1920x1080@119.98, 1920x0, 1
# Xiaomi / Generic (Secondary) - HDMI-A-1
monitor=HDMI-A-1, 1920x1080@60, 0x0, 1

# Vibrance Shader Toggle
bind = SUPER ALT, V, exec, hyprctl keyword decoration:screen_shader ~/.config/hypr/shaders/mi_vibrance.glsl
bind = SUPER ALT SHIFT, V, exec, hyprctl keyword decoration:screen_shader ""

# Window Rules
windowrulev2 = opacity 0.7 0.7 override, class:^(com.mastermindzh.tidal-hifi)$

windowrulev2 = blur override, class:^(com.mastermindzh.tidal-hifi)$
windowrulev2 = blurglass override, class:^(com.mastermindzh.tidal-hifi)$
windowrulev2 = opacity 0.7 0.7, title:^(TIDAL HI-FI)$
windowrulev2 = blur, title:^(TIDAL HI-FI)$
windowrulev2 = blurglass, title:^(TIDAL HI-FI)$
